# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  sgn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-sgorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sgorg.sg.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.sgorg.sg.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:cuzdc65Q -d'
    volumes:
      - ./crypto-config/peerOrganizations/sgorg.sg.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerSGOrg
    networks:
      - sgn

  orderer.sg.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.sg.com
    container_name: orderer.sg.com
    networks:
      - sgn

  peer0.sgorg.sg.com:
    container_name: peer0.sgorg.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sgorg.sg.com
    networks:
      - sgn

  peer1.sgorg.sg.com:
    container_name: peer1.sgorg.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sgorg.sg.com
    networks:
      - sgn

