# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  sgn:

services:

  orderer.sg.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.sg.com
    container_name: orderer.sg.com
    networks:
      - sgn

  peer0.sgorg.sg.com:
    container_name: peer0.sgorg.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.sgorg.sg.com
    networks:
      - sgn

  peer1.sgorg.sg.com:
    container_name: peer1.sgorg.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.sgorg.sg.com
    networks:
      - sgn

  peer0.org2.sg.com:
    container_name: peer0.org2.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.sg.com
    networks:
      - sgn

  peer1.org2.sg.com:
    container_name: peer1.org2.sg.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.sg.com
    networks:
      - sgn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.sgorg.sg.com:7051
      - CORE_PEER_LOCALMSPID=SGOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sgorg.sg.com/peers/peer0.sgorg.sg.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sgorg.sg.com/peers/peer0.sgorg.sg.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sgorg.sg.com/peers/peer0.sgorg.sg.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sgorg.sg.com/users/Admin@sgorg.sg.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.sg.com
      - peer0.sgorg.sg.com
      - peer1.sgorg.sg.com
      - peer0.org2.sg.com
      - peer1.org2.sg.com
    networks:
      - sgn

